
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 47
#define YY_END_OF_BUFFER 48
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[358] =
    {   0,
        0,    0,   48,   46,   45,   19,   46,   22,   28,   46,
        1,   20,   23,   24,    2,   21,   39,   39,   33,   25,
       34,   25,   42,   42,   29,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   30,   18,   26,    0,   43,   34,   31,    0,   16,
       17,   40,    0,    4,   40,   37,    0,    0,   40,    0,
       39,    0,    0,    0,    0,   39,    0,   27,   25,   27,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,    7,   42,   42,   42,   42,   42,   42,   42,
       42,    7,   42,   42,   42,   42,   42,   42,   42,   42,

       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   32,   44,   40,   40,    0,    0,    0,    0,    4,
       40,    0,   37,   37,    0,    0,   36,    0,   40,    0,
       38,   37,   36,   38,   39,    0,   39,   27,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,    5,   42,   42,
       42,   11,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       12,   42,   42,   42,    0,   40,    3,   40,    0,    0,
       40,   36,   36,    0,   40,   40,    0,    0,    0,   38,

       38,    0,    0,   37,    0,   36,    0,   38,    0,   39,
        0,   42,   42,   42,   42,   42,    9,   10,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,    6,   42,
       42,   42,   42,   13,   42,   15,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,    8,   42,   42,
       41,   42,   42,   40,    0,   40,    0,    0,    0,    0,
       38,    0,    0,   40,   38,    0,   38,    0,   38,    0,
       42,   42,   42,   42,   11,   14,   42,   42,   42,   42,
       12,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,    9,   42,   42,   40,   38,

        0,   40,   40,    0,   38,   38,   38,    0,   38,   38,
       35,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   40,   40,    0,
       38,   38,   38,   38,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   10,   42,   42,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    5,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   26,   28,   29,   28,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   32,
       30,   30,   33,   30,   30,   30,   30,   34,   30,   30,
        1,    1,    1,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   30,   46,   47,   48,   49,
       50,   51,   30,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    4,
        4,    5,    4,    4,    1,    6,    3,    3,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        5,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[375] =
    {   0,
        0,    0,  916,  917,  917,  892,  910,  890,   59,    0,
      917,  889,   55,   54,   52,   64,   74,  119,  917,   50,
      888,   52,    0,  856,  886,   42,   47,   76,   44,   49,
       72,  857,   76,  856,   90,   91,  862,   85,   37,  852,
      855,  107,  917,  917,  894,  890,  917,  917,  884,  917,
      917,  154,  880,    0,  135,  183,  217,   67,  917,  168,
      917,  244,  190,  140,  271,  231,  258,  863,  917,  144,
        0,  830,  825,  821,  818,  821,  802,  135,  803,  797,
      777,  783,  769,  770,  767,  767,  773,  766,  764,  761,
      758,    0,  760,  138,  761,  750,  745,  754,  761,  148,

      760,  743,  746,   97,  744,  749,  744,   59,  173,  133,
      747,  917,  917,    0,  917,  303,  287,  774,  203,    0,
      308,  322,    0,  917,  335,  339,  329,  221,  345,    0,
      372,  350,  389,  421,    0,  361,  399,  760,  733,  719,
      731,  724,  733,  728,  727,  717,  703,  701,  150,  716,
      714,  710,  698,  704,  690,  705,  704,    0,  680,  115,
      675,  687,  676,  673,  670,  670,  659,  660,  655,  645,
      647,  644,  647,  650,  636,  649,  634,  631,  627,  634,
        0,  634,  629,  618,  225,  448,  654,    0,  410,  312,
      461,  438,  917,  279,  476,  917,  415,  451,  342,  503,

      351,  535,  464,    0,  489,  519,  405,  571,  477,    0,
      540,  613,  609,  604,  614,  608,    0,    0,  609,  599,
      588,  592,  581,  583,  580,  584,  577,  569,    0,  580,
      568,  582,  554,    0,  545,    0,  558,  556,  551,  540,
      530,  524,  525,  510,  495,  499,  493,    0,  477,  480,
        0,  473,  485,  586,  544,  599,  555,  532,  627,  533,
        0,  543,  426,  631,  667,  488,    0,  545,  694,  487,
      474,  477,  457,  473,    0,    0,  450,  451,  450,  446,
      435,  433,  419,  422,  428,  389,  381,  353,  357,  356,
      345,  353,  330,  338,  320,  317,  324,  314,  661,    0,

      311,    0,  424,  615,    0,  721,    0,  307,    0,  748,
        0,  303,  285,  277,  264,  264,  248,  261,  262,  256,
      251,  250,  226,  237,  228,  228,  221,  763,  917,  708,
        0,  790,    0,    0,  212,  224,  215,  215,  216,  213,
      201,  202,  180,  186,  168,  171,  179,  177,  171,  161,
      152,  132,   98,    0,  100,   60,  917,  832,  838,  842,
      848,  854,  860,   83,  866,  870,  874,  878,  882,  886,
      890,  894,  898,  902
    } ;

static yyconst flex_int16_t yy_def[375] =
    {   0,
      357,    1,  357,  357,  357,  357,  358,  357,  357,  359,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  360,  360,  357,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  357,  357,  357,  358,  358,  357,  357,  357,  357,
      357,  357,  361,  362,  357,  357,  357,  357,  357,  357,
      357,  363,  357,  357,  363,   18,  357,  357,  357,  357,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  357,  357,   52,  357,  357,  357,  361,  361,  362,
      357,  357,   56,  357,  357,  357,  357,  357,  357,  364,
      365,   56,  357,  365,   66,  357,   66,  357,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  357,  357,  361,  121,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  366,  364,  134,

      364,  364,  367,  132,  357,  357,  357,  134,  368,  137,
      357,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  357,  357,  357,  357,  366,  357,  366,
      200,  369,  357,  357,  200,  370,  208,  371,  208,  372,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  357,  265,

      373,  264,  260,  260,  200,  200,  269,  374,  208,  134,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  357,  357,  357,
      265,  306,  269,  134,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,    0,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357
    } ;

static yyconst flex_int16_t yy_nxt[982] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   11,   12,
       13,   11,   14,   15,   16,   17,   18,   18,   18,   19,
       11,   20,   21,   22,   19,   23,   23,   23,   23,   23,
       23,   23,   24,   23,   25,   23,   26,   27,   28,   29,
       30,   31,   32,   23,   33,   23,   34,   23,   35,   23,
       36,   37,   38,   39,   23,   40,   41,   23,   23,   23,
       11,   42,   11,   43,   48,   50,   51,   52,   52,   52,
       52,   68,   69,   53,   69,   70,   47,   47,   54,   73,
      108,   47,  127,  127,   82,  198,   47,   55,  109,   56,
       56,   56,   57,   83,   74,   84,   75,   85,   76,   92,

       58,   59,   60,  177,   61,   77,   86,   62,   87,   63,
      178,   64,   78,   59,   60,   59,   88,   92,   89,   79,
       61,   90,   80,   93,   94,   81,   96,   99,  103,   47,
       97,   65,   55,  172,   66,   66,   66,   66,  104,  105,
      356,  106,  100,  107,   98,  101,   59,   60,  173,   61,
      121,  121,  121,  121,   67,  133,  133,  355,   59,   60,
       59,  230,   59,  122,  231,   61,   47,  138,  112,  114,
      114,  114,  114,  354,   59,  122,   59,  182,  128,  183,
      128,  115,  116,  129,  129,  129,  129,  145,  146,  117,
      161,  162,  167,  115,  116,  115,   55,  168,  123,  123,

      123,   57,  221,  222,  248,  132,  132,  132,   57,  179,
       59,   60,  119,  124,  275,  353,  248,  187,  125,  181,
      352,  351,   59,   60,   59,   63,  276,  180,  350,  124,
       55,  181,   57,   57,   57,   57,  129,  129,  129,  129,
      186,  186,  186,  186,   59,   60,  135,  135,  135,  135,
      349,  234,  126,  348,  347,  346,   59,   60,   59,  131,
      131,  131,  131,  345,  158,  158,  136,  344,  343,  131,
      131,  131,  131,  137,  137,  137,  137,  342,  341,  340,
      131,  131,  131,  131,  131,  131,  134,  134,  134,  134,
       92,  229,  339,   67,  192,  192,  134,  134,  134,  134,

      338,  337,  114,  114,  114,  114,  234,  134,  134,  134,
      134,  134,  134,  185,  194,  185,  275,  229,  186,  186,
      186,  186,  117,  188,  188,  188,  188,  191,  191,  191,
      191,  336,  190,   92,  190,   59,  122,  191,  191,  191,
      191,  335,  308,  189,  192,  192,  301,   59,  122,   59,
      123,  123,  123,   57,   57,   57,   57,   57,  327,  193,
      195,  195,  195,  195,  194,  204,  204,  204,  326,  218,
      125,  325,  196,  259,  126,  193,  135,  135,  135,  135,
      197,  229,  259,  324,  196,  205,  196,  200,  200,  200,
      200,  181,  259,  218,  217,  323,  136,  200,  200,  200,

      200,  259,  201,  202,  206,  206,  322,  203,  200,  200,
      200,  200,  200,  200,  210,  210,  210,  210,  201,  193,
      206,  206,  202,  321,  207,  188,  188,  188,  188,  276,
      195,  195,  195,  195,  211,  193,  208,  208,  208,  208,
      207,  299,  299,  299,  299,  189,  208,  208,  208,  208,
      197,  201,  202,  192,  192,  259,  209,  208,  208,  208,
      208,  208,  208,  254,  254,  254,  254,  201,  193,  320,
      319,  202,  217,  194,  259,  115,  256,  256,  256,  256,
      318,  317,  259,  255,  193,  316,  260,  115,   59,  115,
      248,  195,  195,  195,  195,  259,  257,  315,  314,  266,

       59,  259,   59,  196,  204,  204,  204,   57,  259,  313,
      229,  197,  270,  312,  259,  196,  311,  196,  261,  261,
      261,  261,  270,  266,  205,  158,  298,  259,  261,  261,
      261,  261,  297,  296,  206,  206,  295,  294,  262,  261,
      261,  261,  261,  261,  261,  263,  276,  263,  293,  193,
      264,  264,  264,  264,  207,  210,  210,  210,  210,  254,
      254,  254,  254,  259,  357,  193,  259,  260,  260,  292,
      256,  256,  256,  256,  259,  211,  259,  275,  301,  255,
      308,  291,  259,  357,  290,  259,  267,  267,  267,  267,
      257,  289,  288,  259,  287,  259,  267,  267,  267,  267,

      286,  254,  254,  254,  254,  285,  268,  267,  267,  267,
      267,  267,  267,  115,  256,  256,  256,  256,  284,  283,
      282,  255,  276,  281,  251,  115,   59,  115,  280,  279,
      302,  302,  302,  302,  257,  278,  277,  263,   59,  263,
       59,  276,  299,  299,  299,  299,  302,  302,  302,  302,
      304,  234,  275,  248,  274,  273,  258,  258,  303,  258,
      272,  271,  259,  119,  253,  252,  304,  258,  258,  258,
      303,  258,  303,  234,  251,  250,  328,  328,  328,  328,
      249,  259,  305,  305,  305,  305,  248,  247,  329,  246,
      245,  244,  305,  305,  305,  305,  330,  243,  242,  241,

      329,  240,  329,  305,  305,  305,  305,  305,  305,  309,
      309,  309,  309,  239,  238,  237,  236,  235,  234,  309,
      309,  309,  309,  328,  328,  328,  328,  233,  232,  229,
      309,  309,  309,  309,  309,  309,  332,  332,  332,  332,
      228,  227,  226,  330,  225,  218,  332,  332,  332,  332,
      217,  224,  223,  220,  181,  219,  203,  332,  332,  332,
      332,  332,  332,  334,  334,  334,  334,  218,  217,  216,
      215,  214,  213,  334,  334,  334,  334,  212,  328,  328,
      328,  328,   47,  119,  334,  334,  334,  334,  334,  334,
      329,  184,  176,  175,  174,  171,  170,  169,  330,  166,

      165,  158,  329,  164,  329,  200,  200,  200,  200,  163,
      160,  159,  158,  157,  156,  200,  200,  200,  200,  155,
      154,  153,  152,  151,  150,  149,  200,  200,  200,  200,
      200,  200,   45,  148,   45,   45,   45,   45,   49,  147,
       49,   49,   49,   49,   71,   71,   71,   71,  118,  118,
      118,  118,  118,  118,  120,  144,  120,  120,  120,  120,
      130,  143,  130,  130,  130,  130,  199,  142,  199,  199,
      199,  199,  258,  141,  258,  258,  265,  140,  265,  265,
      269,  139,  269,  269,  300,   47,  300,  300,  306,  119,
      113,  306,  307,   46,  307,  307,  310,   46,  111,  310,

      331,  110,  102,  331,  333,   95,   91,  333,   47,   72,
       44,   47,   47,   46,   44,  357,    3,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357
    } ;

static yyconst flex_int16_t yy_chk[982] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,   13,   14,   15,   15,   15,
       15,   20,   20,   16,   22,   22,   14,   13,   16,   26,
       39,    9,   58,   58,   29,  364,   16,   17,   39,   17,
       17,   17,   17,   29,   26,   30,   27,   30,   27,  356,

       17,   17,   17,  108,   17,   27,   30,   17,   31,   17,
      108,   17,   28,   17,   17,   17,   31,   33,   31,   28,
       17,   31,   28,   33,   33,   28,   35,   36,   38,   42,
       35,   17,   18,  104,   18,   18,   18,   18,   38,   38,
      355,   38,   36,   38,   35,   36,   18,   18,  104,   18,
       55,   55,   55,   55,   18,   64,   64,  353,   18,   18,
       18,  160,   55,   55,  160,   18,   70,   70,   42,   52,
       52,   52,   52,  352,   55,   55,   55,  110,   60,  110,
       60,   52,   52,   60,   60,   60,   60,   78,   78,   52,
       94,   94,  100,   52,   52,   52,   56,  100,   56,   56,

       56,   56,  149,  149,  351,   63,   63,   63,   63,  109,
       56,   56,  119,   56,  350,  349,  348,  119,   56,  347,
      346,  345,   56,   56,   56,   63,  344,  109,  343,   56,
       57,  109,   57,   57,   57,   57,  128,  128,  128,  128,
      185,  185,  185,  185,   57,   57,   66,   66,   66,   66,
      342,  341,   57,  340,  339,  338,   57,   57,   57,   62,
       62,   62,   62,  337,  336,  335,   66,  327,  326,   62,
       62,   62,   62,   67,   67,   67,   67,  325,  324,  323,
       62,   62,   62,   62,   62,   62,   65,   65,   65,   65,
      322,  321,  320,   67,  194,  194,   65,   65,   65,   65,

      319,  318,  117,  117,  117,  117,  317,   65,   65,   65,
       65,   65,   65,  116,  194,  116,  316,  315,  116,  116,
      116,  116,  117,  121,  121,  121,  121,  190,  190,  190,
      190,  314,  122,  313,  122,  121,  121,  122,  122,  122,
      122,  312,  308,  121,  127,  127,  301,  121,  121,  121,
      125,  125,  125,  125,  126,  126,  126,  126,  298,  127,
      129,  129,  129,  129,  127,  132,  132,  132,  297,  296,
      125,  295,  129,  199,  126,  127,  136,  136,  136,  136,
      129,  294,  201,  293,  129,  132,  129,  131,  131,  131,
      131,  292,  199,  291,  290,  289,  136,  131,  131,  131,

      131,  201,  131,  131,  133,  133,  288,  131,  131,  131,
      131,  131,  131,  131,  137,  137,  137,  137,  131,  133,
      207,  207,  131,  287,  133,  189,  189,  189,  189,  286,
      197,  197,  197,  197,  137,  133,  134,  134,  134,  134,
      207,  263,  263,  263,  263,  189,  134,  134,  134,  134,
      197,  134,  134,  192,  192,  303,  134,  134,  134,  134,
      134,  134,  134,  186,  186,  186,  186,  134,  192,  285,
      284,  134,  283,  192,  303,  186,  191,  191,  191,  191,
      282,  281,  198,  186,  192,  280,  198,  186,  191,  186,
      279,  195,  195,  195,  195,  203,  191,  278,  277,  203,

      191,  198,  191,  195,  205,  205,  205,  205,  209,  274,
      273,  195,  209,  272,  203,  195,  271,  195,  200,  200,
      200,  200,  270,  266,  205,  253,  252,  209,  200,  200,
      200,  200,  250,  249,  206,  206,  247,  246,  200,  200,
      200,  200,  200,  200,  200,  202,  245,  202,  244,  206,
      202,  202,  202,  202,  206,  211,  211,  211,  211,  255,
      255,  255,  255,  258,  260,  206,  202,  258,  260,  243,
      257,  257,  257,  257,  262,  211,  268,  242,  262,  255,
      268,  241,  258,  260,  240,  202,  208,  208,  208,  208,
      257,  239,  238,  262,  237,  268,  208,  208,  208,  208,

      235,  254,  254,  254,  254,  233,  208,  208,  208,  208,
      208,  208,  208,  254,  256,  256,  256,  256,  232,  231,
      230,  254,  228,  227,  226,  254,  256,  254,  225,  224,
      304,  304,  304,  304,  256,  223,  222,  259,  256,  259,
      256,  221,  259,  259,  259,  259,  264,  264,  264,  264,
      304,  220,  219,  216,  215,  214,  264,  264,  264,  264,
      213,  212,  264,  187,  184,  183,  264,  264,  264,  264,
      264,  264,  264,  182,  180,  179,  299,  299,  299,  299,
      178,  264,  265,  265,  265,  265,  177,  176,  299,  175,
      174,  173,  265,  265,  265,  265,  299,  172,  171,  170,

      299,  169,  299,  265,  265,  265,  265,  265,  265,  269,
      269,  269,  269,  168,  167,  166,  165,  164,  163,  269,
      269,  269,  269,  330,  330,  330,  330,  162,  161,  159,
      269,  269,  269,  269,  269,  269,  306,  306,  306,  306,
      157,  156,  155,  330,  154,  153,  306,  306,  306,  306,
      152,  151,  150,  148,  147,  146,  306,  306,  306,  306,
      306,  306,  306,  310,  310,  310,  310,  145,  144,  143,
      142,  141,  140,  310,  310,  310,  310,  139,  328,  328,
      328,  328,  138,  118,  310,  310,  310,  310,  310,  310,
      328,  111,  107,  106,  105,  103,  102,  101,  328,   99,

       98,   97,  328,   96,  328,  332,  332,  332,  332,   95,
       93,   91,   90,   89,   88,  332,  332,  332,  332,   87,
       86,   85,   84,   83,   82,   81,  332,  332,  332,  332,
      332,  332,  358,   80,  358,  358,  358,  358,  359,   79,
      359,  359,  359,  359,  360,  360,  360,  360,  361,  361,
      361,  361,  361,  361,  362,   77,  362,  362,  362,  362,
      363,   76,  363,  363,  363,  363,  365,   75,  365,  365,
      365,  365,  366,   74,  366,  366,  367,   73,  367,  367,
      368,   72,  368,  368,  369,   68,  369,  369,  370,   53,
       49,  370,  371,   46,  371,  371,  372,   45,   41,  372,

      373,   40,   37,  373,  374,   34,   32,  374,   25,   24,
       21,   12,    8,    7,    6,    3,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[48] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "trial.l"
#line 2 "trial.l"
#include "mylex.h"	
/* DECIMAL LITERAL */
/* HEXADECIMAL LITERAL */
/* OCTAL LITERAL */
/* BINARY LITERAL */
/* FLOATING POINT LITERAL */
#line 815 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 65 "trial.l"

#line 997 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 358 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 917 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 66 "trial.l"
{printf("\n Separator: %s",yytext); return 10;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 67 "trial.l"
{printf("\n Dot operator"); return 10;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 68 "trial.l"
{ return 10;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 69 "trial.l"
{ return 10;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 70 "trial.l"
{printf("\n Keyword: %s",yytext); return 10;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 71 "trial.l"
{printf("\n Keyword: %s",yytext); return 10;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 72 "trial.l"
{printf("\n Keyword: %s",yytext); return 10;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 73 "trial.l"
{printf("\n Keyword: %s",yytext); return 10;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 74 "trial.l"
{printf("\n Keyword: %s",yytext); return 10;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 75 "trial.l"
{printf("\n Keyword: %s",yytext); return 10;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 76 "trial.l"
{printf("\n Keyword: %s",yytext); return 10;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 77 "trial.l"
{printf("\n Keyword: %s",yytext); return 10;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 78 "trial.l"
{printf("\n Keyword: %s",yytext); return 10;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 79 "trial.l"
{printf("\n Keyword: %s",yytext); return 10;}   	         
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 80 "trial.l"
{printf("\n Null: %s",yytext); return 10;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 81 "trial.l"
{printf("\n Increment operator: %s",yytext); return 10;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 82 "trial.l"
{printf("\n Decrement operator: %s",yytext); return 10;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 83 "trial.l"
{printf("\n not operator: %s",yytext); return 10;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 84 "trial.l"
{printf("\n not operator: %s",yytext); return 10;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 85 "trial.l"
{printf("\n multiplication operator: %s",yytext); return 10;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 86 "trial.l"
{printf("\n Division operator: %s",yytext); return 10;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 87 "trial.l"
{printf("\n Modulus operator: %s",yytext); return 10;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 88 "trial.l"
{printf("\n addition operator: %s",yytext); return 10;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 89 "trial.l"
{printf("\n subtraction operator: %s",yytext); return 10;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 90 "trial.l"
{printf("\n relational operator: %s",yytext); return 10;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 91 "trial.l"
{printf("\n equality operator: %s",yytext); return 10;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 92 "trial.l"
{printf("\n shift operator: %s",yytext); return 10;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 93 "trial.l"
{printf("\n Bitwise AND operator: %s",yytext); return 10;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 94 "trial.l"
{printf("\n Bitwise exclusive OR operator: %s",yytext); return 10;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 95 "trial.l"
{printf("\n Bitwise inclusive OR operator: %s",yytext); return 10;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 96 "trial.l"
{printf("\n Logical AND operator: %s",yytext); return 10;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 97 "trial.l"
{printf("\n Logical OR operator: %s",yytext); return 10;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 98 "trial.l"
{printf("\n ternary operator: %s",yytext); return 10;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 99 "trial.l"
{printf("\n assignment operator: %s",yytext); return 10;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 100 "trial.l"
{printf("\n Data Type: String"); return 10;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 102 "trial.l"
{printf("\n Integer Constant: %s",yytext); return INTEGER_LITERAL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 103 "trial.l"
{printf("\n Integer Constant: %s",yytext); return INTEGER_LITERAL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 104 "trial.l"
{printf("\n Integer Constant: %s",yytext); return INTEGER_LITERAL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 105 "trial.l"
{printf("\n Integer Constant: %s",yytext); return INTEGER_LITERAL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 106 "trial.l"
{printf("\n Floating-Point Literal: %s",yytext); return FLOAT_LITERAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 107 "trial.l"
{printf("\n Boolean Literal: %s",yytext); return BOOLEAN_LITERAL;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 109 "trial.l"
{printf("\n Identifier: %s",yytext); return IDENTIFIER;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 112 "trial.l"
{printf("\n String is %s",yytext); return STRING_LITERAL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 113 "trial.l"
{printf("\n Character Constant: %s",yytext); return CHAR_LITERAL;}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 114 "trial.l"
{return 10;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 115 "trial.l"
{return 10;};
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 119 "trial.l"
ECHO;
	YY_BREAK
#line 1327 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 358 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 358 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 357);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 119 "trial.l"


int yywrap(void){
	return 1;
}




/*

TODO:
1. Strings,characters, and comments
*/

